name: Syntax Check

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Check JavaScript syntax
      run: |
        # Verificar sintaxis de todos los archivos JS
        find . -name "*.js" -not -path "./node_modules/*" | xargs -I {} node --check {}
    
    - name: Run ESLint
      run: npm run lint
      # Asegúrate de tener el script "lint" en tu package.json
